version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      maven-dependencies:
        patterns: [ "*" ]
    ignore:
      - dependency-name: "org.graalvm.buildtools:native-maven-plugin"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
