include "vendors"

printers = [
  {
    "id": 123, # Not sure if this it's the one I've
    "model": "TM-T88IV",
    "features": {  
      "barcode": {
        "available": [ "upc-a", "upc-e", "ean13", "ean8", "code39", "itf", "codabar", "code93", "code128" ]
      }
    }
  }
]
