include "vendors"

printers = [
  {
    "id": 3586, # 0x0e02
    "model": "TM-T88IV",
    "features": {  
      "barcode": {
        "available": [ "upc-a", "upc-e", "ean13", "ean8", "code39", "itf", "codabar", "code93", "code128" ]
      }
    }
  }
]
