#!/usr/bin/env python3
"""Fetch the escpos-printer-db capability database and emit it as HOCON.

Downloads the latest release's "Source code (zip)" from
https://github.com/receipt-print-hq/escpos-printer-db, extracts
``dist/capabilities.json``, converts it to HOCON, and writes it to
``faradn-core/src/main/resources/capabilities.conf``.

The generated file records the source version in a header comment. On a later
run the script resolves the latest version, compares it against that comment,
and skips the (large) download and conversion when it is already current -
unless ``--force`` is given.

Standard library only; no third-party packages required. Set ``GITHUB_TOKEN``
(or pass ``--token``) to lift the unauthenticated GitHub API rate limit.
"""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import sys
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

REPO = "receipt-print-hq/escpos-printer-db"
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "faradn-core" / "src" / "main" / "resources" / "capabilities.conf"
CAPABILITIES_ENTRY = "dist/capabilities.json"
VERSION_MARKER = "# escpos-printer-db version:"

# A HOCON key may stay unquoted only when it is a simple identifier; anything
# else (numeric slots, dots, symbols) must be quoted to parse unambiguously.
SAFE_KEY = re.compile(r"[A-Za-z_][A-Za-z0-9_-]*")


def http_get(url: str, token: str | None, accept: str = "application/vnd.github+json") -> bytes:
    headers = {"User-Agent": "faradn-capabilities-fetch", "Accept": accept}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request) as response:
        return response.read()


def resolve_latest(repo: str, token: str | None) -> tuple[str, str]:
    """Return ``(version_tag, zipball_url)`` for the latest release.

    Falls back to the newest tag when the repository publishes tags but no
    formal GitHub releases.
    """
    try:
        data = json.loads(http_get(f"https://api.github.com/repos/{repo}/releases/latest", token))
        return data["tag_name"], data["zipball_url"]
    except urllib.error.HTTPError as exc:
        if exc.code != 404:
            raise
    tags = json.loads(http_get(f"https://api.github.com/repos/{repo}/tags", token))
    if not tags:
        raise SystemExit(f"{repo} has no releases or tags to download")
    return tags[0]["name"], tags[0]["zipball_url"]


def recorded_version(path: Path) -> str | None:
    """The version noted in an existing output file's header, if any."""
    if not path.exists():
        return None
    with path.open(encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if line.startswith(VERSION_MARKER):
                return line[len(VERSION_MARKER):].strip()
            if line and not line.startswith("#"):
                break  # reached the body without finding a marker
    return None


def extract_capabilities(zipball: bytes) -> dict:
    with zipfile.ZipFile(io.BytesIO(zipball)) as archive:
        entry = next((name for name in archive.namelist() if name.endswith(CAPABILITIES_ENTRY)), None)
        if entry is None:
            raise SystemExit(f"{CAPABILITIES_ENTRY} not found in the source archive")
        with archive.open(entry) as handle:
            return json.load(handle)


def hocon_key(key: str) -> str:
    return key if SAFE_KEY.fullmatch(key) else json.dumps(key, ensure_ascii=False)


def render_object(obj: dict, indent: int, out: list[str]) -> None:
    """Append the HOCON body of ``obj`` (no enclosing braces) to ``out``.

    Nested objects use ``key { ... }``; every other value (scalars and arrays)
    is emitted as ``key = <json>``, which is valid HOCON since HOCON is a JSON
    superset.
    """
    pad = "  " * indent
    for key, value in obj.items():
        name = hocon_key(key)
        if isinstance(value, dict) and value:
            out.append(f"{pad}{name} {{")
            render_object(value, indent + 1, out)
            out.append(f"{pad}}}")
        elif isinstance(value, dict):
            out.append(f"{pad}{name} {{}}")
        else:
            out.append(f"{pad}{name} = {json.dumps(value, ensure_ascii=False)}")


def to_hocon(data: dict, version: str, repo: str) -> str:
    if not isinstance(data, dict):
        raise SystemExit("capabilities.json root is not a JSON object")
    out = [
        "# Generated by scripts/fetch_capabilities.py. Do not edit by hand.",
        f"# Source: https://github.com/{repo}",
        f"{VERSION_MARKER} {version}",
        "",
    ]
    render_object(data, 0, out)
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--force", action="store_true",
                        help="re-download and regenerate even if already current")
    parser.add_argument("--profiles-only", action="store_true",
                        help="drop the large 'encodings' tables, keeping only printer profiles")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                        help=f"output .conf path (default: {DEFAULT_OUTPUT})")
    parser.add_argument("--repo", default=REPO, help=f"GitHub owner/repo (default: {REPO})")
    parser.add_argument("--token", default=os.environ.get("GITHUB_TOKEN"),
                        help="GitHub token, or set $GITHUB_TOKEN, to lift the API rate limit")
    args = parser.parse_args(argv)

    print(f"Resolving the latest release of {args.repo} ...")
    version, zipball_url = resolve_latest(args.repo, args.token)
    print(f"Latest version: {version}")

    current = recorded_version(args.output)
    if current == version and not args.force:
        print(f"{args.output} is already at {version}; nothing to do "
              "(pass --force to regenerate).")
        return 0
    if current and current != version:
        print(f"Updating {current} -> {version}.")

    print("Downloading the source archive ...")
    zipball = http_get(zipball_url, args.token, accept="application/zip")

    print("Extracting and converting capabilities.json ...")
    data = extract_capabilities(zipball)
    if args.profiles_only:
        data = {key: value for key, value in data.items() if key != "encodings"}

    hocon = to_hocon(data, version, args.repo)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(hocon, encoding="utf-8")
    print(f"Wrote {args.output} ({len(hocon):,} bytes) at version {version}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
